### ISSUE TITLE
Missing Font 

### ISSUE THREAD

**Issue by Emily3403** [ducksaucewithmsg/trans-neofetch#2]
Hey, my font doesnt have the special symbols needed for displaying the neofetch output. 

Which font do you use?

**Comment by ducksaucewithmsg** [comment]
my terminal is alacritty `https://github.com/alacritty/alacritty`
my font is JetBrainsMono Nerd Font `https://github.com/ryanoasis/nerd-fonts`

this is my font.yml file as a txt file
[fonts.txt](https://github.com/ducksaucewithmsg/trans-neofetch/files/8681662/fonts.txt)
